# Generated by Django 2.0.2 on 2018-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INVESTMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateField()),
                ('investment_time', models.TimeField()),
                ('investment_price', models.FloatField()),
                ('investment_amount', models.FloatField()),
            ],
        ),
    ]
